brew "zplug"

cask "figma"
cask "flipper"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "jetbrains-toolbox"
cask "visual-studio-code"

vscode "dracula-theme.theme-dracula"
vscode "ms-python.python"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
