---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    name: Integration
    runs-on: macos-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: /Users/runner/.local/share/mac-os-setup

      - name: Uninstall GitHub Actions' built-in Homebrew
        run: . ~/.local/share/mac-os-setup/tests/uninstall-homebrew.sh

      - name: Test install script
        run: . ~/.local/share/mac-os-setup/install.sh
