---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    name: Integration
    runs-on: macos-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Uninstall GitHub Actions' built-in Homebrew
        run: ./tests/uninstall-homebrew.sh

      - name: Test install script
        run: ./install.sh
